### ISSUE TITLE
raw access to $_GET/$_POST/$_REQUEST is not allowed

### ISSUE THREAD

**Issue by danmarsden** [miroslavfikar/moodle-assignsubmission_random#11]
https://github.com/miroslavfikar/moodle-assignsubmission_random/blob/master/locallib.php#L256

please check all your code and make sure you do not use the raw $_GET/$_POST or $_REQUEST vars - please use the moodle apis optional/required_param instead

more information on this is here:
https://moodledev.io/general/development/policies/security#dont-trust-any-input-from-users

note this is a blocker for plugins db approval.

**Comment by miroslavfikar** [comment]
There are no more any $_GET/$_POST or $_REQUEST vars in the code, closing the issue.
