### ISSUE TITLE
incorrect repository structure.

### ISSUE THREAD

**Issue by danmarsden** [miroslavfikar/moodle-assignsubmission_random#6]
the structure of your repositories is non-standard and will prevent many people that use git to manage their plugin deployments from using your plugins.

Ideally the code should sit in the root of your repository - that way organisations can use git submodules / subtrees etc to deploy your code into their sites.

note - this is not a blocker for approval in the plugins db but it will annoy a lot of Moodle admins - using the correct structure also comes with a few other benefits - including the ability to use github actions (I'll create another issue to cover that)

**Comment by miroslavfikar** [comment]
directory structure reorganised according to standards
